### PR TITLE
basic login page using google auth

### PR DESCRIPTION
**Pull request by IEatPencils**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Do the .idea files need to be included, or are those files used by your IDE?

**Comment by IEatPencils** [comment]
> Do the .idea files need to be included, or are those files used by your IDE?

These are IDE specific that I setup for debugging purposes, I can remove them real quick

**Comment by ghost** [comment]
Before we merge into main, we need to resolve the merge conflicts. This conflict stems from the fact that all the files have been moved up one directory, and the root Pokinaturalists directory (which held Pokinaturalists, pokinaturalist, and inaturalist) is now removed. I can sort out this merge conflict, unless you want to

**Comment by ghost** [comment]
Resolved merge conflicts between main and PN-62

**Comment by ghost** [comment]
Is login supposed to be its own app, or is it supposed to be within Pokinaturalists (where settings.py is)? 

Are there any additional python libraries we have to install? Such as allauth? If so, can you add them to the requirements.txt?

If you are working in a venv, you can pip install -r requirements, and then pip freeze > requirements.txt.

**Comment by ghost** [comment]
Moved the login app to its proper location and updated requirements. Can you add some directions on how to go about logging in with Google?

**Comment by IEatPencils** [comment]
im updating the read me with it as we speak, plus i've redone how its made

**Review by CasualNerd729 — APPROVED** [review]

**Comment by CasualNerd729** [comment]
Oop reviewed that without realizing that it still needs more work. Oh well.

**Pull request merged**
